interface OrderData {
    order: string;
    customer: string;
    channel: string;
    date: string;
    total: string;
    status: string;
  }
  
 export const data: OrderData[] = [
    {
      order: "#1234",
      customer: "Evelyn Scott",
      channel: "Online Store",
      date: "April 20, 2023",
      total: "$37.40",
      status: "Shipped",
    },
  
    {
      order: "#3456",
      customer: "Michael Young",
      channel: "Online Store",
      date: "May 17, 2023",
      total: "$64.75",
      status: "Shipped",
    },
  
    {
      order: "#5678",
      customer: "Emily Hall",
      channel: "Online Store",
      date: "June 28, 2023",
      total: "$19.99",
      status: "Shipped",
    },
  
    {
      order: "#7890",
      customer: "Alexander King",
      channel: "Online Store",
      date: "July 15, 2023",
      total: "$53.60",
      status: "Shipped",
    },
  
    {
      order: "#8901",
      customer: "Ava Wright",
      channel: "Online Store",
      date: "August 9, 2023",
      total: "$76.25",
      status: "Shipped",
    },
  
    {
      order: "#9012",
      customer: "Daniel Adams",
      channel: "Online Store",
      date: "September 3, 2023",
      total: "$42.90",
      status: "Shipped",
    },
  
    {
      order: "#1123",
      customer: "Olivia Brown",
      channel: "Online Store",
      date: "October 22, 2023",
      total: "$57.80",
      status: "Shipped",
    },
    {
      order: "#3201",
      customer: "Priya",
      channel: "Online Store",
      date: "February 04, 2024",
      total: "$105.25",
      status: "Shipped",
    },
    {
      order: "#3202",
      customer: "Jayam",
      channel: "Online Store",
      date: "June 10, 2024",
      total: "$60.35",
      status: "Panding",
    },
    {
      order: "#3208",
      customer: "Kalai",
      channel: "Shop",
      date: "July 04, 2024",
      total: "$55.70",
      status: "Panding",
    },
    {
      order: "#3204",
      customer: "Gayathri",
      channel: "Shop",
      date: "June 28, 2022",
      total: "$120.99",
      status: "Paid",
    },
    {
      order: "#3205",
      customer: "Bob",
      channel: "Online Store",
      date: "February 30, 2024",
      total: "$132.00",
      status: "Paid",
    },
    {
      order: "#3209",
      customer: "Ava Johnson",
      channel: "Shop",
      date: "January 5, 2022",
      total: "$81.99",
      status: "Shipped",
    },
    {
      order: "#3299",
      customer: "Johnson",
      channel: "Shop",
      date: "January 5, 2022",
      total: "$32.99",
      status: "Paid",
    },
    {
      order: "#3278",
      customer: "gaya",
      channel: "Online Store",
      date: "January 5, 2022",
      total: "$49.99",
      status: "Paid",
    },
    {
      order: "#3109",
      customer: "John",
      channel: "Shop",
      date: "January 5, 2022",
      total: "$74.99",
      status: "Shipped",
    },
    {
      order: "#3165",
      customer: "Johnson",
      channel: "Online Store",
      date: "January 5, 2022",
      total: "$86.99",
      status: "Paid",
    },
    {
      order: "#3232",
      customer: "bob",
      channel: "Shop",
      date: "January 5, 2022",
      total: "$36.99",
      status: "Shipped",
    },
    {
      order: "#3680",
      customer: "Sisiy",
      channel: "Online Store",
      date: "January 5, 2022",
      total: "$22.99",
      status: "Paid",
    },
    {
      order: "#3550",
      customer: "admin",
      channel: "Shop",
      date: "January 5, 2022",
      total: "$45.99",
      status: "Shipped",
    },
    {
      order: "#3203",
      customer: "lovely",
      channel: "Online Store",
      date: "January 5, 2022",
      total: "$21.99",
      status: "Paid",
    },
    {
      order: "#3073",
      customer: "swift",
      channel: "Shop",
      date: "January 5, 2022",
      total: "$69.99",
      status: "Shipped",
    },
    {
      order: "#3571",
      customer: "raam",
      channel: "Online Store",
      date: "January 5, 2022",
      total: "$90.99",
      status: "Paid",
    },
    {
      order: "#3678",
      customer: "jay",
      channel: "Shop",
      date: "January 5, 2022",
      total: "$112.99",
      status: "Paid",
    },
    {
      order: "#3405",
      customer: "mainly",
      channel: "Online Store",
      date: "January 5, 2022",
      total: "$48.99",
      status: "Paid",
    },
    {
        order: "#3701",
        customer: "Lisa Smith",
        channel: "Online Store",
        date: "February 10, 2024",
        total: "$85.75",
        status: "Shipped",
      },
      {
        order: "#3702",
        customer: "Ethan Brown",
        channel: "Shop",
        date: "February 14, 2024",
        total: "$40.25",
        status: "Panding",
      },
      {
        order: "#3703",
        customer: "Sophia Davis",
        channel: "Online Store",
        date: "March 5, 2024",
        total: "$60.50",
        status: "Paid",
      },
      {
        order: "#3704",
        customer: "Jackson Lee",
        channel: "Shop",
        date: "March 12, 2024",
        total: "$74.99",
        status: "Shipped",
      },
      {
        order: "#3705",
        customer: "Mia Wilson",
        channel: "Online Store",
        date: "April 1, 2024",
        total: "$45.00",
        status: "Paid",
      },
      {
        order: "#3706",
        customer: "William Martinez",
        channel: "Shop",
        date: "April 15, 2024",
        total: "$89.10",
        status: "Panding",
      },
      {
        order: "#3707",
        customer: "Ava Taylor",
        channel: "Online Store",
        date: "May 5, 2024",
        total: "$55.85",
        status: "Shipped",
      },
      {
        order: "#3708",
        customer: "James Anderson",
        channel: "Shop",
        date: "May 20, 2024",
        total: "$70.20",
        status: "Paid",
      },
      {
        order: "#3709",
        customer: "Charlotte Thomas",
        channel: "Online Store",
        date: "June 3, 2024",
        total: "$80.45",
        status: "Paid",
      },
      {
        order: "#3710",
        customer: "Benjamin Harris",
        channel: "Shop",
        date: "June 18, 2024",
        total: "$92.99",
        status: "Shipped",
      },
      {
        order: "#3711",
        customer: "Amelia Clark",
        channel: "Online Store",
        date: "July 7, 2024",
        total: "$66.60",
        status: "Shipped",
      },
      {
        order: "#3712",
        customer: "Lucas Lewis",
        channel: "Shop",
        date: "July 22, 2024",
        total: "$50.75",
        status: "Panding",
      },
      {
        order: "#3713",
        customer: "Isabella Walker",
        channel: "Online Store",
        date: "August 10, 2024",
        total: "$72.30",
        status: "Paid",
      },
      {
        order: "#3714",
        customer: "Oliver Scott",
        channel: "Shop",
        date: "August 25, 2024",
        total: "$85.90",
        status: "Shipped",
      },
      {
        order: "#3715",
        customer: "Evelyn Young",
        channel: "Online Store",
        date: "September 5, 2024",
        total: "$99.99",
        status: "Paid",
      },
      {
        order: "#3716",
        customer: "Elijah Green",
        channel: "Shop",
        date: "September 20, 2024",
        total: "$64.55",
        status: "Panding",
      },
      {
        order: "#3717",
        customer: "Harper Adams",
        channel: "Online Store",
        date: "October 4, 2024",
        total: "$90.40",
        status: "Shipped",
      },
      {
        order: "#3718",
        customer: "Logan Nelson",
        channel: "Shop",
        date: "October 18, 2024",
        total: "$56.20",
        status: "Paid",
      },
      {
        order: "#3719",
        customer: "Mia Baker",
        channel: "Online Store",
        date: "November 2, 2024",
        total: "$68.75",
        status: "Shipped",
      },
      {
        order: "#3720",
        customer: "James Rodriguez",
        channel: "Shop",
        date: "November 17, 2024",
        total: "$77.85",
        status: "Panding",
      },
      {
        order: "#3721",
        customer: "Lily Green",
        channel: "Online Store",
        date: "December 1, 2024",
        total: "$40.50",
        status: "Paid",
      },
      {
        order: "#3722",
        customer: "Henry Martinez",
        channel: "Shop",
        date: "December 15, 2024",
        total: "$93.00",
        status: "Shipped",
      },
      {
        order: "#3723",
        customer: "Chloe White",
        channel: "Online Store",
        date: "January 10, 2025",
        total: "$85.60",
        status: "Paid",
      },
  ];